TF-12644 / using utils test functions to reuse on similar pages
clearviction-devs/clearviction-wa pull request #240
Opened 2024-04-01 14:23 UTC by LeoFuna

### Ticket(s)

_Required unless this is just a change to documentation._

- _[12644](https://airtable.com/appfJZShN8K4tcWHU/pagXdnDYi0tVl4u8R?HjEAY=recYozpvCTDg0Lc55)_

### Type of change

- [x] Documentation or testing

### Description

We had some duplication of code on many fishing violation page tests, so we will use util functions to help o remove them.

Fixes # _replace with issue number that this fixes_

### Review your work

### Overall PR Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings in the console
- [x] There are no new linting errors/problems in my code
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] I have filled out the new 3rd party dependency checklist (if applicable)
- [x] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand

2024-04-03 21:18 UTC, e-papanicolas requested changes
@leofuna just the one assert name update. I love this cleanup!

2024-04-03 21:18 UTC, e-papanicolas commented on cypress/e2e/misdemeanor/utils/haveNecessaryInfoAssert.ts
Leo can we just rename this assert to "hasNecessaryInfoAssert" ? 🙏🏼

2024-04-04 12:07 UTC, LeoFuna commented on cypress/e2e/misdemeanor/utils/haveNecessaryInfoAssert.ts
Yeah! Make more sense, thx

2024-04-05 15:44 UTC, e-papanicolas approved these changes

2024-04-05 15:44 UTC, merged