Scrum s303 save export results
clearviction-devs/clearviction-wa pull request #67
Opened 2023-08-02 12:50 UTC by mhyneman8

### Ticket(s)

### Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description

We created a download results button. This will allow the user to take their calculator results to someone else or print for future use.

html2canvas 
jspdf

These two work together to be able to download the component we made. jspdf creates the pdf and html2canvas keeps the styling like the page.

There is no ticket, because it was deleted during the sprint

### Screenshots

Include relevant screenshots.

#### Before
![image](https://github.com/clearviction-devs/clearviction-wa/assets/59981297/d87375ac-108d-4ae4-8ff1-3336085d6894)

#### After
![image](https://github.com/clearviction-devs/clearviction-wa/assets/59981297/7723d06b-1118-429f-9862-38ad72579639)

![localhost_3000_calculator_offense-fish-5-eligible](https://github.com/clearviction-devs/clearviction-wa/assets/59981297/657ee7f0-5d5c-4dd2-9bb9-e3b2d3a53459)

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings in the console
- [ ] There are no new linting errors/problems in my code
- [ ] I have filled this PR out fully, and cleaned up any extraneous items so that it is clear and easy to understand

2023-08-02 20:19 UTC, e-papanicolas requested changes

2023-08-02 20:19 UTC, e-papanicolas commented on components/helper/Results.tsx
> +// import React, { useState } from 'react';
Remove extra commented out import.

2023-08-02 20:19 UTC, e-papanicolas commented on components/helper/Results.tsx
> +}
Needs one extra line of spacer below.

2023-08-02 20:19 UTC, e-papanicolas commented on components/helper/Results.tsx
> +// import {ImageContainer} from '../layout/ImageContainer.jsx';
The image container should be available now!

2023-08-05 18:12 UTC, mhyneman8 commented
@e-papanicolas fixed the comments. The download is a little tough because it prints whatever is on the screen, which means it has to be a certain width to print appropriately. So I added an automatic close for screen sizes under 901. The pdf is on the screen long enough for it to be saved and then closes. 

Open to other ideas if you can think of them.

2023-08-06 17:57 UTC, e-papanicolas approved these changes
🥳

2023-08-06 17:59 UTC, merged